In [1]:
# 1. Khai báo thư viện
import pandas as pd
import numpy as np
# 2. Nạp dữ liệu TikTok Shop vào DataFrame
df = pd.read_csv('tiktok_shop_sales.csv')
# 3. Xem kích thước (Số dòng, Số cột) của dữ liệu
print(f"Tổng số dòng: {df.shape[0]}")
print(f"Tổng số cột: {df.shape[1]}")
# 4. Hiển thị 5 dòng dữ liệu đầu tiên
df.head()

Tổng số dòng: 8500
Tổng số cột: 27

,Order_ID,Order_Date,Customer_ID,Customer_Name,Customer_Age,Customer_Gender,Shipping_City,Device_Type,Product_ID,Product_Name,...,Payment_Method,Order_Status,Product_Rating,Review_Count,Shop_ID,Shop_Name,Traffic_Source,Creator_Name,Video_Views,Is_Anomaly
0,TTS-2024-000001,2024-08-10 23:03:34,CUST-00058,Trần Hoàng Phong,24,Nam,Hà Nội,iOS (iPhone),PROD-B04,Kem chống nắng Anessa Perfect UV Sunscreen,...,COD (Thanh toán khi nhận hàng),Hoàn thành,4.0,7200,SHOP-007,Audio SoundMaster Mall,Showcase (Cửa hàng),None (Gian hàng trực tiếp),99674,0
1,TTS-2024-000002,2024-05-24 19:11:57,CUST-00454,Dương Minh Nam,44,Nam,TP. Hồ Chí Minh,Android,PROD-T03,Giá đỡ điện thoại để bàn livestream xoay 360,...,Ví điện tử (ZaloPay/Momo),Đã hủy,3.0,13400,SHOP-002,GenZ Streetwear Studio,Livestream TikTok,Tun Phạm,1014151,1
2,TTS-2024-000003,2024-09-13 12:23:58,CUST-00824,Vũ Phương Vy,25,Nữ,Cần Thơ,Android,PROD-B03,Nước tẩy trang L'Oreal Micellar Water 400ml,...,COD (Thanh toán khi nhận hàng),Hoàn thành,5.0,15600,SHOP-005,Smart Home Tiện Ích 365,Tìm kiếm TikTok,None (Tìm kiếm tự nhiên),49590,0
3,TTS-2024-000004,2024-04-16 22:26:24,CUST-00570,Trần Hà Quỳnh,33,Nữ,Đà Nẵng,Android,PROD-F05,Váy hoa nhí tay bồng phong cách Hàn Quốc,...,Ví điện tử (ZaloPay/Momo),Hoàn thành,5.0,4300,SHOP-004,Bếp Mẹ Nấu & Đồ Ăn Vặt,Livestream TikTok,Quyền Leo Daily,690596,0
4,TTS-2024-000005,2024-07-09 19:47:16,CUST-01395,Lê Hà Nhi,41,Nữ,Đà Nẵng,iOS (iPhone),PROD-S02,Khô gà lá chanh cay cay đậm đà 500g,...,COD (Thanh toán khi nhận hàng),Hoàn thành,3.0,19500,SHOP-004,Bếp Mẹ Nấu & Đồ Ăn Vặt,Video ngắn gắn link,Tun Phạm,1775699,0

In [2]:
# Kiểm tra thông tin cấu trúc và kiểu dữ liệu
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8500 entries, 0 to 8499
Data columns (total 27 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order_ID         8500 non-null   object
 1   Order_Date       8500 non-null   object
 2   Customer_ID      8500 non-null   object
 3   Customer_Name    8500 non-null   object
 4   Customer_Age     8500 non-null   int64
 5   Customer_Gender  8500 non-null   object
 6   Shipping_City    8500 non-null   object
 7   Device_Type      8500 non-null   object
 8   Product_ID       8500 non-null   object
 9   Product_Name     8500 non-null   object
 10  Main_Category    8500 non-null   object
 11  Sub_Category     8500 non-null   object
 12  Unit_Price       8500 non-null   int64
 13  Quantity         8500 non-null   int64
 14  Discount_Amount  8500 non-null   int64
 15  Shipping_Fee     8500 non-null   int64
 16  Total_Amount     8500 non-null   int64
 17  Payment_Method   8500 non-null   object
 18  Order_Status     8500 non-null   object
 19  Product_Rating   8500 non-null   float64
 20  Review_Count     8500 non-null   int64
 21  Shop_ID          8500 non-null   object
 22  Shop_Name        8500 non-null   object
 23  Traffic_Source   8500 non-null   object
 24  Creator_Name     8500 non-null   object
 25  Video_Views      8500 non-null   int64
 26  Is_Anomaly       8500 non-null   int64
dtypes: float64(1), int64(9), object(17)
memory usage: 1.8+ MB

In [3]:
# Thống kê số lượng giá trị khuyết thiếu
print(" 1. SỐ LƯỢNG GIÁ TRỊ NULL TRÊN TỪNG CỘT ")
print(df.isnull().sum())

# 2.Kiểm tra số lượng dòng bị trùng lặp hoàn toàn
duplicates_count = df.duplicated().sum()
print(f"\n 2. TỔNG SỐ DÒNG BỊ TRÙNG LẶP HOÀN TOÀN: {duplicates_count} dòng")

 1. SỐ LƯỢNG GIÁ TRỊ NULL TRÊN TỪNG CỘT
Order_ID           0
Order_Date         0
Customer_ID        0
Customer_Name      0
Customer_Age       0
Customer_Gender    0
Shipping_City      0
Device_Type        0
Product_ID         0
Product_Name       0
Main_Category      0
Sub_Category       0
Unit_Price         0
Quantity           0
Discount_Amount    0
Shipping_Fee       0
Total_Amount       0
Payment_Method     0
Order_Status       0
Product_Rating     0
Review_Count       0
Shop_ID            0
Shop_Name          0
Traffic_Source     0
Creator_Name       0
Video_Views        0
Is_Anomaly         0
dtype: int64

 2. TỔNG SỐ DÒNG BỊ TRÙNG LẶP HOÀN TOÀN: 0 dòng

In [4]:
# Kiểm tra các giá trị khác biệt trong cột Người sáng tạo / KOC (Creator_Name)
print(" 1. CÁC GIÁ TRỊ KHÁC BIỆT CỦA CỘT Creator_Name ")
print(df['Creator_Name'].value_counts().head(8))

# Kiểm tra các giá trị khác biệt của Tỉnh / Thành phố (Shipping_City)
print("\n 2. DANH SÁCH TỈNH / THÀNH PHỐ (Shipping_City) ---")
print(df['Shipping_City'].unique())

# Kiểm tra các trạng thái đơn hàng (Order_Status)
print("\n3. TRẠNG THÁI ĐƠN HÀNG (Order_Status)")
print(df['Order_Status'].value_counts())

 1. CÁC GIÁ TRỊ KHÁC BIỆT CỦA CỘT Creator_Name
Creator_Name
None (Gian hàng trực tiếp)    1001
Call Me Duy                    764
Lê Dương Bảo Lâm               746
Trinh Phạm                     737
Võ Hà Linh                     730
Diệp Lê                        726
Tun Phạm                       717
Phạm Thoại                     706
Name: count, dtype: int64

 2. DANH SÁCH TỈNH / THÀNH PHỐ (Shipping_City) ---
['Hà Nội' 'TP. Hồ Chí Minh' 'Cần Thơ' 'Đà Nẵng' 'Bình Dương' 'Hải Phòng'
 'Đồng Nai' 'Thừa Thiên Huế' 'Thái Nguyên' 'Bắc Ninh' 'Lâm Đồng'
 'Quảng Ninh' 'Khánh Hòa' 'Vũng Tàu']

3. TRẠNG THÁI ĐƠN HÀNG (Order_Status)
Order_Status
Hoàn thành               6926
Đang vận chuyển           651
Đã hủy                    522
Hoàn trả / Khiếu nại      276
Giao không thành công     125
Name: count, dtype: int64

In [5]:
# Tạo bản sao df_clean để làm sạch
df_clean = df.copy()

# Xóa cột thừa không phục vụ phân tích đơn hàng (cột Is_Anomaly)
if 'Is_Anomaly' in df_clean.columns:
    df_clean.drop(columns=['Is_Anomaly'], inplace=True)
    print("-> [XONG] Đã xóa cột thừa: Is_Anomaly")

# Chuyển đổi cột Order_Date từ kiểu chữ (object) sang đúng kiểu Ngày Giờ (datetime)
df_clean['Order_Date'] = pd.to_datetime(df_clean['Order_Date'])
print(f"-> [XONG] Kiểu dữ liệu mới của Order_Date: {df_clean['Order_Date'].dtype}")

# So sánh số lượng cột Trước (Before) và Sau (After)
print(f"\n SO SÁNH SỐ CỘT")
print(f"Trước khi làm sạch (Before): {df.shape[1]} cột")
print(f"Sau khi làm sạch (After) : {df_clean.shape[1]} cột")

-> [XONG] Đã xóa cột thừa: Is_Anomaly
-> [XONG] Kiểu dữ liệu mới của Order_Date: datetime64[ns]

 SO SÁNH SỐ CỘT
Trước khi làm sạch (Before): 27 cột
Sau khi làm sạch (After) : 26 cột

In [6]:
# Chuẩn hóa giá trị khuyết thiếu ngầm ở cột Creator_Name
df_clean['Creator_Name'] = df_clean['Creator_Name'].replace(
    'None (Gian hàng trực tiếp)',
    'Bán trực tiếp (Không qua KOC)')
print("-> [XONG] Đã chuẩn hóa giá trị thiếu ngầm ở cột Creator_Name.")

# Cột số (Customer_Age) nếu có khuyết sẽ điền bằng median (trung vị)
median_age = df_clean['Customer_Age'].median()
df_clean['Customer_Age'] = df_clean['Customer_Age'].fillna(median_age)

# Cột phân loại (Shipping_City) nếu có khuyết sẽ điền bằng mode (giá trị phổ biến nhất)
mode_city = df_clean['Shipping_City'].mode()[0]
df_clean['Shipping_City'] = df_clean['Shipping_City'].fillna(mode_city)
print(f"-> [XONG] Đã cấu hình chiến lược Impute: Age (Median={median_age}), City (Mode='{mode_city}').")

# Loại bỏ dòng rác: Xóa các dòng bị khuyết trường khóa chính Order_ID (nếu có)
rows_before = len(df_clean)
df_clean = df_clean.dropna(subset=['Order_ID'])
df_clean = df_clean.dropna(how='all') # Xóa dòng trống hoàn toàn
print(f"-> [XONG] Kiểm tra khóa chính: Giữ vững {len(df_clean)}/{rows_before} dòng hợp lệ.")

# Hiển thị lại tỷ lệ phân bổ của Creator_Name sau chuẩn hóa
print("\n--- PHÂN BỔ KOC/CREATOR SAU KHI XỬ LÝ KHUYẾT THIẾU ---")
print(df_clean['Creator_Name'].value_counts().head(5))

-> [XONG] Đã chuẩn hóa giá trị thiếu ngầm ở cột Creator_Name.
-> [XONG] Đã cấu hình chiến lược Impute: Age (Median=24.0), City (Mode='TP. Hồ Chí Minh').
-> [XONG] Kiểm tra khóa chính: Giữ vững 8500/8500 dòng hợp lệ.

--- PHÂN BỔ KOC/CREATOR SAU KHI XỬ LÝ KHUYẾT THIẾU ---
Creator_Name
Bán trực tiếp (Không qua KOC)    1001
Call Me Duy                       764
Lê Dương Bảo Lâm                  746
Trinh Phạm                        737
Võ Hà Linh                        730
Name: count, dtype: int64

In [7]:
# Loại bỏ trùng lặp hoàn toàn (nếu có)
df_clean = df_clean.drop_duplicates()

# Xử lý trùng lặp một phần theo khóa chính Order_ID:
# Nếu trùng mã đơn hàng, sắp xếp theo thời gian và giữ lại bản ghi mới nhất
df_clean = df_clean.sort_values('Order_Date').drop_duplicates(subset=['Order_ID'], keep='last')
df_clean.reset_index(drop=True, inplace=True)
print(f"-> [XONG] Đảm bảo tính duy nhất tuyệt đối: {df_clean['Order_ID'].nunique()}/{len(df_clean)} đơn hàng.")

# BẢNG TỔNG KẾT ĐỐI CHIẾU TRƯỚC VÀ SAU KHI LÀM SẠCH (BEFORE VS AFTER)
print("\n" + "="*60)
print("       BẢNG ĐỐI CHIẾU KẾT QUẢ TRƯỚC VÀ SAU KHI LÀM SẠCH")
print("="*60)
summary_data = {
    "Tiêu chí": [
        "Tổng số dòng (Rows)",
        "Tổng số cột thuộc tính (Columns)",
        "Kiểu dữ liệu cột Order_Date",
        "Số giá trị khuyết ngầm Creator_Name",
        "Cột rác / thừa (Is_Anomaly)",
        "Tính duy nhất của Order_ID"
    ],
    "Trước khi làm sạch (Before)": [
        f"{df.shape[0]} dòng",
        f"{df.shape[1]} cột",
        str(df['Order_Date'].dtype) + " (Chuỗi ký tự/object)",
        f"{df['Creator_Name'].str.contains('None', na=False).sum()} dòng ('None')",
        "Có tồn tại (1 cột rác)",
        "Chưa kiểm soát xung đột"
    ],
    "Sau khi làm sạch (After)": [
        f"{df_clean.shape[0]} dòng",
        f"{df_clean.shape[1]} cột (Đã tinh gọn)",
        str(df_clean['Order_Date'].dtype) + " (Chuẩn thời gian)",
        f"{df_clean['Creator_Name'].str.contains('None', na=False).sum()} dòng (Đã gán nhãn chuẩn)",
        "Đã loại bỏ hoàn toàn (0 cột)",
        "100% Duy nhất (Unique)"]}
df_summary = pd.DataFrame(summary_data)
display(df_summary)

-> [XONG] Đảm bảo tính duy nhất tuyệt đối: 8500/8500 đơn hàng.

============================================================
       BẢNG ĐỐI CHIẾU KẾT QUẢ TRƯỚC VÀ SAU KHI LÀM SẠCH
============================================================

,Tiêu chí,Trước khi làm sạch (Before),Sau khi làm sạch (After)
0,Tổng số dòng (Rows),8500 dòng,8500 dòng
1,Tổng số cột thuộc tính (Columns),27 cột,26 cột (Đã tinh gọn)
2,Kiểu dữ liệu cột Order_Date,object (Chuỗi ký tự/object),datetime64[ns] (Chuẩn thời gian)
3,Số giá trị khuyết ngầm Creator_Name,1674 dòng ('None'),673 dòng (Đã gán nhãn chuẩn)
4,Cột rác / thừa (Is_Anomaly),Có tồn tại (1 cột rác),Đã loại bỏ hoàn toàn (0 cột)
5,Tính duy nhất của Order_ID,Chưa kiểm soát xung đột,100% Duy nhất (Unique)