In [1]:
# Cài đặt thư viện kết nối MongoDB
!pip install pymongo dnspython -q

from pymongo import MongoClient
import pandas as pd
import numpy as np

# Kết nối tới Cloud MongoDB Atlas của nhóm
CONNECTION_STRING = "mongodb+srv://24126088_db_user:d7LxVqEQejBP@cluster0.e1l29uo.mongodb.net/?retryWrites=true&w=majority"
client = MongoClient(CONNECTION_STRING)
db = client["ecommerce"]
collection = db["transactions"]

# Nạp dữ liệu vào DataFrame
df = pd.DataFrame(list(collection.find()))

print(f"-> [THÀNH CÔNG] Đã kết nối MongoDB Atlas!")
print(f"-> Tổng số dòng: {df.shape[0]} dòng, {df.shape[1]} cột thuộc tính.")
df.head(3)

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 13.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 354.8/354.8 kB 14.8 MB/s eta 0:00:00
-> [THÀNH CÔNG] Đã kết nối MongoDB Atlas!
-> Tổng số dòng: 8500 dòng, 31 cột thuộc tính.

,_id,Order_ID,Order_Date,Customer_ID,Customer_Name,Customer_Age,Customer_Gender,Shipping_City,Device_Type,Product_ID,...,Review_Count,Shop_ID,Shop_Name,Traffic_Source,Creator_Name,Video_Views,Is_Anomaly,Category,Age,Gender
0,6ad5f6886af58f1037265fa1,TTS-2024-000008,2024-03-28 20:46:28,CUST-00052,Vũ Thành Khang,32,Nam,Bình Dương,iOS (iPhone),PROD-S05,...,27000,SHOP-002,GenZ Streetwear Studio,Livestream TikTok,Trinh Phạm,387872,0,Đồ ăn vặt & Thực phẩm,32,Nam
1,6ad5f6886af58f1037265fa2,TTS-2024-000009,2024-08-28 20:09:57,CUST-00213,Nguyễn Minh Tùng,22,Nam,Đà Nẵng,iOS (iPhone),PROD-M01,...,16400,SHOP-001,Beauty Queen Official Store,Video ngắn gắn link,Lê Dương Bảo Lâm,1648399,0,Thời trang nam,22,Nam
2,6ad5f6886af58f1037265fa7,TTS-2024-000014,2024-06-21 19:42:11,CUST-00560,Hoàng Phương Quỳnh,23,Nữ,Hà Nội,iOS (iPhone),PROD-F02,...,9800,SHOP-008,SkinCare Hub Chính Hãng,Livestream TikTok,Lê Dương Bảo Lâm,697587,0,Thời trang nữ,23,Nữ

In [3]:
# Kiểm tra cấu trúc, kiểu dữ liệu, ô trống Null và dòng trùng lặp
print("CẤU TRÚC VÀ KIỂU DỮ LIỆU")
print(df.info())

print("\nKIỂM TRA GIÁ TRỊ NULL VÀ TRÙNG LẶP")
print(f"Số ô Null toàn bảng: {df.isnull().sum().sum()}")
print(f"Số dòng trùng lặp: {df.duplicated().sum()}")

print("\nKHẢO SÁT GIÁ TRỊ CỘT Creator_Name")
print(df['Creator_Name'].value_counts().head(5))

CẤU TRÚC VÀ KIỂU DỮ LIỆU
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8500 entries, 0 to 8499
Data columns (total 31 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   _id              8500 non-null   object
 1   Order_ID         8500 non-null   object
 2   Order_Date       8500 non-null   object
 3   Customer_ID      8500 non-null   object
 4   Customer_Name    8500 non-null   object
 5   Customer_Age     8500 non-null   int64
 6   Customer_Gender  8500 non-null   object
 7   Shipping_City    8500 non-null   object
 8   Device_Type      8500 non-null   object
 9   Product_ID       8500 non-null   object
 10  Product_Name     8500 non-null   object
 11  Main_Category    8500 non-null   object
 12  Sub_Category     8500 non-null   object
 13  Unit_Price       8500 non-null   float64
 14  Quantity         8500 non-null   int64
 15  Discount_Amount  8500 non-null   float64
 16  Shipping_Fee     8500 non-null   float64
 17  Total_Amount     8500 non-null   float64
 18  Payment_Method   8500 non-null   object
 19  Order_Status     8500 non-null   object
 20  Product_Rating   8500 non-null   float64
 21  Review_Count     8500 non-null   int64
 22  Shop_ID          8500 non-null   object
 23  Shop_Name        8500 non-null   object
 24  Traffic_Source   8500 non-null   object
 25  Creator_Name     8500 non-null   object
 26  Video_Views      8500 non-null   int64
 27  Is_Anomaly       8500 non-null   int64
 28  Category         8500 non-null   object
 29  Age              8500 non-null   int64
 30  Gender           8500 non-null   object
dtypes: float64(5), int64(6), object(20)
memory usage: 2.0+ MB
None

KIỂM TRA GIÁ TRỊ NULL VÀ TRÙNG LẶP
Số ô Null toàn bảng: 0
Số dòng trùng lặp: 0

KHẢO SÁT GIÁ TRỊ CỘT Creator_Name
Creator_Name
None (Gian hàng trực tiếp)    1001
Call Me Duy                    764
Lê Dương Bảo Lâm               746
Trinh Phạm                     737
Võ Hà Linh                     730
Name: count, dtype: int64

In [5]:
df_clean = df.copy()
# Xóa các cột hệ thống MongoDB và cột thừa/trùng lặp
cols_to_drop = [c for c in ['_id', 'Is_Anomaly', 'Category', 'Age', 'Gender'] if c in df_clean.columns]
df_clean.drop(columns=cols_to_drop, inplace=True)
# Chuẩn hóa Order_Date sang kiểu thời gian datetime64
df_clean['Order_Date'] = pd.to_datetime(df_clean['Order_Date'])
# Chuẩn hóa giá trị thiếu ngầm ở Creator_Name
df_clean['Creator_Name'] = df_clean['Creator_Name'].replace('None (Gian hàng trực tiếp)', 'Bán trực tiếp (Không qua KOC)')
# Cấu hình Impute: Tuổi (Median), Thành phố (Mode)
df_clean['Customer_Age'] = df_clean['Customer_Age'].fillna(df_clean['Customer_Age'].median())
df_clean['Shipping_City'] = df_clean['Shipping_City'].fillna(df_clean['Shipping_City'].mode()[0])
# Loại bỏ trùng lặp và bảo đảm tính duy nhất của Order_ID
df_clean = df_clean.sort_values('Order_Date').drop_duplicates(subset=['Order_ID'], keep='last')
df_clean.reset_index(drop=True, inplace=True)
summary_data = {
    "Tiêu chí": [
        "Tổng số dòng (Rows)",
        "Tổng số cột thuộc tính (Columns)",
        "Cột ID hệ thống MongoDB (_id)",
        "Cột rác / thừa (Is_Anomaly, Category, Age, Gender)",
        "Kiểu dữ liệu cột Order_Date",
        "Số giá trị khuyết ngầm Creator_Name",
        "Tính duy nhất của Order_ID" ],
    "Trước khi làm sạch (Before)": [
        f"{df.shape[0]} dòng",
        f"{df.shape[1]} cột",
        "Có tồn tại (_id)",
        "Tồn tại 4 cột rác/trùng",
        str(df['Order_Date'].dtype) + " (Chuỗi ký tự/object)",
        f"{df['Creator_Name'].str.contains('None', na=False).sum()} dòng ('None')",
        "Chưa kiểm soát xung đột"],
    "Sau khi làm sạch (After)": [
        f"{df_clean.shape[0]} dòng",
        f"{df_clean.shape[1]} cột (Đã tinh gọn chuẩn)",
        "Đã loại bỏ hoàn toàn",
        "Đã loại bỏ hoàn toàn",
        str(df_clean['Order_Date'].dtype) + " (Chuẩn thời gian)",
        f"{df_clean['Creator_Name'].str.contains('None', na=False).sum()} dòng (Đã gán nhãn chuẩn)",
        "100% Duy nhất (Unique)"]}
display(pd.DataFrame(summary_data))

,Tiêu chí,Trước khi làm sạch (Before),Sau khi làm sạch (After)
0,Tổng số dòng (Rows),8500 dòng,8500 dòng
1,Tổng số cột thuộc tính (Columns),31 cột,26 cột (Đã tinh gọn chuẩn)
2,Cột ID hệ thống MongoDB (_id),Có tồn tại (_id),Đã loại bỏ hoàn toàn
3,"Cột rác / thừa (Is_Anomaly, Category, Age, Gen...",Tồn tại 4 cột rác/trùng,Đã loại bỏ hoàn toàn
4,Kiểu dữ liệu cột Order_Date,object (Chuỗi ký tự/object),datetime64[ns] (Chuẩn thời gian)
5,Số giá trị khuyết ngầm Creator_Name,1674 dòng ('None'),673 dòng (Đã gán nhãn chuẩn)
6,Tính duy nhất của Order_ID,Chưa kiểm soát xung đột,100% Duy nhất (Unique)

In [6]:
# Xuất dữ liệu sạch ra tệp CSV để thành viên 3A tiếp nối thực hiện
output_file = "tiktok_shop_clean_step2.csv"
df_clean.to_csv(output_file, index=False, encoding='utf-8-sig')

print(f"-> [THÀNH CÔNG] ĐÃ KẾT XUẤT TỆP: {output_file}")
print(f"-> Kích thước: {df_clean.shape[0]} dòng, {df_clean.shape[1]} cột.")

-> [THÀNH CÔNG] ĐÃ KẾT XUẤT TỆP: tiktok_shop_clean_step2.csv
-> Kích thước: 8500 dòng, 26 cột.